class OnboardException(Exception): ...
class APIConnectionError(OnboardException, ConnectionError): ...
class InitialConnectionError(APIConnectionError): ...
class DataInvalidError(OnboardException): ...
class NotImplementedInAPIError(OnboardException, NotImplementedError): ...
